### ISSUE TITLE
Image Processing New Enhancemant

### ISSUE THREAD

**Issue by TechMaverik** [TechMaverik/Snoopy_Guardian#8]
- [ ] Detects motion via camera
- [x] Obstacle Detection
- [ ] Human Detection
- [ ] Track an Object from the camera when a sample is provided
- [x] Traffic Light

**Comment by abdulahad01** [comment]
What type of obstacles are we detecting using cv?

**Comment by HLRobotics** [comment]
Humans, Any object Edge Detection, Traffic signs,

**Comment by abdulahad01** [comment]
I can set up a simple edge detector, I'll look into a more flexible traffic sign classifier using tensorflow, please give me a few days time.

**Comment by HLRobotics** [comment]
sure

**Comment by HLRobotics** [comment]
@abdulahad01 please take a new branch from main and put a Pull Request once it is done ok.
